import { Providers } from '@/components'
import '@/styles/globals.css'
import c from 'clsx'
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export interface RootLayoutProps {
	children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html
			lang='en'
			className={c('scroll-smooth antialiased flex w-full h-full', GeistMono.variable, GeistSans.variable)}
			suppressHydrationWarning
		>
			<body className='overflow-x-hidden text-sm  flex w-full h-full text-primary dark:bg-primary dark:text-primary-dark md:text-base lg:text-base'>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
